### ISSUE TITLE
More than two outcomes

### ISSUE THREAD

**Issue by ddebeer** [JeroenDMulder/powRICLPM#11]
Thank you for the helpful package!

The functionality of powRICLPM seems to be limited to two outcomes. That is, only a 2x2 matrix can be used as a Phi. Is an extension to more than two outcomes possible? And is this something you plan to develop?

Thanks and best regards.

**Comment by JeroenDMulder** [comment]
Hi @ddebeer, thank you for your question. In principle it is possible to extend this power analysis approach/the package to accommodate power analysis for tri- or morevariate versions of the CLPM, RI-CLPM, and STARTS. However, one of the issues that needs to be tackled when going to a more-variate version of the model, is that it becomes increasingly difficult to specify population parameter values that combined allow you to simulate data from it. This is related the first limitation that is mentioned in [Mulder (2023)](https://doi.org/10.1080/10705511.2022.2122467), see Section 6.1.

I originally planned to work on this last summer, but unfortunately I have not gotten round to it. I don't have plans to implement this in the foreseeable future.

**Comment by ddebeer** [comment]
Thank you for the quick and clear response.
