### ISSUE TITLE
Error in the help file

### ISSUE THREAD

**Issue by vogelgesang** [JeroenDMulder/powRICLPM#4]
Thx for the great package! While reading the help file, I came across this sentence: "Estimating measurement errors (i.e., the STARTS model) is done by setting est_ME = TRUE." It should rather say: Estimating measurement errors (i.e., the STARTS model) is done by setting estimate_ME = TRUE.

**Comment by JeroenDMulder** [comment]
Hi @vogelgesang, thanks for noting this error in the documentation. I'll fix it with the next update of the package, which I hope to have ready by the end of this summer.

**Comment by Eunji23** [comment]
Thanks for the great package. I want to conduct a simulation study with different conditions from you, but I have got an error message as below; 

ℹ Checking arguments...
Error in check_within_cor(within_cor) : 
  `within_cor` must be between 0 and 1:
ℹ A correlation is always between 0 and 1.
✖ Your `within_cor` is -0.42.

I refer to the previous studies about self-esteem and depression, so I need to set up the negative within correlation between two variables in the RI-CLPM. 
How can I conduct a simulation with this condition through your package?
